# Scraping
PAGINATION_ENABLED=False

# MongoDB
MONGO_URL=

# InfluxDB
# INFLUXDB_URL=
# INFLUXDB_ORG=
# INFLUXDB_TOKEN=
# INFLUXDB_BUCKET=

# Notification
NOTIFICATION_DISCOUNT_PERCENTAGE=20
NOTIFICATION_RESTOCK=False

# Notification - Discord
DISCORD_URL=

# Notification - Telegram
# TELEGRAM_TOKEN=
# TELEGRAM_CHAT_ID=
